import type { Metadata } from "next";
import { Poppins, Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import Providers from "../components/ProgressBarProvider";
import { FloatingNav } from "@components/ui/floating-navbar";
import { IconHome, IconMessage, IconUser } from "@tabler/icons-react";

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

const kantumruyPro = Kantumruy_Pro({
    variable: "--font-kantumruy",
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const navItems = [
        {
            name: "Home",
            link: "/",
            icon: <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />,
        },
        {
            name: "About",
            link: "/about",
            icon: <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />,
        },
        {
            name: "Contact",
            link: "/contact",
            icon: (
                <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
            ),
        },
    ];
    return (
        <html lang="en">
            <body className={`${poppins.variable} ${kantumruyPro.variable} antialiased p-0 m-0`}>
                <FloatingNav navItems={navItems} />
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
