name: Clean Node Modules

on:
  push:
    branches:
      - v2

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Remove node_modules and package-lock.json
      run: |
        rm -rf node_modules
        rm -f package-lock.json